const { EmbedBuilder } = require("discord.js");
const crypto = require("crypto");

// Powerful AES-256-CBC Encryption
const ALGORITHM = "aes-256-cbc";
const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY || "interx_3_0_sovereign_secret_key_88"; // Should ideally be 32 chars
const IV_LENGTH = 16;

function encrypt(text) {
    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv(ALGORITHM, Buffer.from(ENCRYPTION_KEY.padEnd(32, "0").slice(0, 32)), iv);
    let encrypted = cipher.update(text);
    encrypted = Buffer.concat([encrypted, cipher.final()]);
    return iv.toString("hex") + ":" + encrypted.toString("hex");
}

function decrypt(text) {
    try {
        const textParts = text.split(":");
        const iv = Buffer.from(textParts.shift(), "hex");
        const encryptedText = Buffer.from(textParts.join(":"), "hex");
        const decipher = crypto.createDecipheriv(ALGORITHM, Buffer.from(ENCRYPTION_KEY.padEnd(32, "0").slice(0, 32)), iv);
        let decrypted = decipher.update(encryptedText);
        decrypted = Buffer.concat([decrypted, decipher.final()]);
        return decrypted.toString();
    } catch (e) {
        return null;
    }
}

module.exports = {
    name: "encryption",
    description: "Secure AES-256-CBC encryption system.",
    aliases: ["encrypt", "decrypt", "crypt"],
    usage: "!encryption <encrypt/decrypt> <text/hash>",

    async execute(message, args) {
        const sub = args[0]?.toLowerCase();
        const content = args.slice(1).join(" ");

        if (!sub || !content) {
            const usage = new EmbedBuilder()
                .setColor("#df0000")
                .setAuthor({ name: "interX CRYPTOGRAPHIC ENGINE", iconURL: message.client.user.displayAvatarURL() })
                .setDescription(
                    `Powerful AES-256-CBC encryption for secure communications.\n\n` +
                    `**COMMANDS:**\n` +
                    `> \`!encrypt <message>\` — Encrypt a message into a secure hash\n` +
                    `> \`!decrypt <hash>\` — Decrypt an interX hash back to text\n\n` +
                    `**NOTE:** Only hashes generated by this bot can be decrypted.`
                )
                .setFooter({ text: "interX Security • Protocol: Military Grade" })
                .setTimestamp();
            return message.reply({ embeds: [usage] });
        }

        if (sub === "encrypt" || message.content.toLowerCase().startsWith(`${process.env.PREFIX || "!"}encrypt`)) {
            const textToEncrypt = sub === "encrypt" ? content : args.join(" ");
            const hash = encrypt(textToEncrypt);

            const embed = new EmbedBuilder()
                .setColor("#df0000")
                .setAuthor({ name: "ENCRYPTION COMPLETE", iconURL: message.author.displayAvatarURL({ dynamic: true }) })
                .setDescription(
                    `### 🔒 DATA SECURED\n` +
                    `Your message has been processed through the Sovereign Cryptographic Engine.\n\n` +
                    `**Generated Hash:**\n\`\`\`js\n${hash}\n\`\`\``
                )
                .setFooter({ text: "interX Security • Algorithm: AES-256-CBC" })
                .setTimestamp();

            // Try to delete original message for privacy
            message.delete().catch(() => { });
            return message.channel.send({ content: `${message.author}, here is your secure payload:`, embeds: [embed] });

        } else if (sub === "decrypt" || message.content.toLowerCase().startsWith(`${process.env.PREFIX || "!"}decrypt`)) {
            const hashToDecrypt = sub === "decrypt" ? content : args.join(" ");
            const result = decrypt(hashToDecrypt);

            if (!result) {
                return message.reply({ content: "❌ **Invalid Hash:** Could not decrypt the provided payload. Ensure it was generated by the Sovereign engine." });
            }

            const embed = new EmbedBuilder()
                .setColor("#df0000")
                .setAuthor({ name: "DECRYPTION COMPLETE", iconURL: message.author.displayAvatarURL({ dynamic: true }) })
                .setDescription(
                    `### 🔓 DATA REVEALED\n` +
                    `The secure hash has been successfully bypassed and translated.\n\n` +
                    `**Decrypted Message:**\n\`\`\`ansi\n\u001b[2;31m${result}\u001b[0m\n\`\`\``
                )
                .setFooter({ text: "interX Security • Source: Sovereign Engine" })
                .setTimestamp();

            return message.reply({ embeds: [embed] });
        } else {
            return message.reply({ content: "❌ **Usage:** `!encrypt <text>` or `!decrypt <hash>`" });
        }
    }
};
